
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#


apiVersion: management.apiconnect.ibm.com/v1beta1
kind: ManagementCluster
metadata:
  name: management
spec:
  version: 12.1.0.3
  imagePullSecrets:
  - ibm-entitlement-key
  imageRegistry: icr.io/apic12
  profile: n1xc2.m16
  portal:
    admin:
      secretName: portal-admin-client
  analytics:
    ingestion:
      secretName: analytics-ingestion-client
  gateway:
    client:
      secretName: gateway-client-client
  devPortal:
    admin:
      secretName: devportal-admin-client
  wmAPIGateway:
    mgmt:
      secretName: wmapigateway-mgmt-client
  nanoGateway:
    mgmt:
      secretName: nano-gateway-mgmt-client
  federatedAPIManagement:
    admin:
      secretName: federatedapimanagement-admin-client
  cloudManagerEndpoint:
    #ingressClassName: $INGRESS_CLASS
    annotations:
    hosts:
    - name: admin.mycluster-eu-de-1-bxf-8x3-e7d3d93b8b317d269525bf063b24f98d-0000.eu-de.containers.appdomain.cloud
      secretName: default-ingress-cert
  apiManagerEndpoint:
    #ingressClassName: $INGRESS_CLASS
    annotations:
    hosts:
    - name: manager.mycluster-eu-de-1-bxf-8x3-e7d3d93b8b317d269525bf063b24f98d-0000.eu-de.containers.appdomain.cloud
      secretName: default-ingress-cert
  consumerCatalogEndpoint:
    #ingressClassName: $INGRESS_CLASS
    annotations:
      cert-manager.io/issuer: ingress-issuer
    hosts:
    - name: consumer-catalog.mycluster-eu-de-1-bxf-8x3-e7d3d93b8b317d269525bf063b24f98d-0000.eu-de.containers.appdomain.cloud
      secretName: consumer-catalog-endpoint
  platformAPIEndpoint:
    #ingressClassName: $INGRESS_CLASS
    annotations:
      cert-manager.io/issuer: ingress-issuer
    hosts:
    - name: api.mycluster-eu-de-1-bxf-8x3-e7d3d93b8b317d269525bf063b24f98d-0000.eu-de.containers.appdomain.cloud
      secretName: api-endpoint
  consumerAPIEndpoint:
    #ingressClassName: $INGRESS_CLASS
    annotations:
      cert-manager.io/issuer: ingress-issuer
    hosts:
    - name: consumer.mycluster-eu-de-1-bxf-8x3-e7d3d93b8b317d269525bf063b24f98d-0000.eu-de.containers.appdomain.cloud
      secretName: consumer-endpoint
  databaseVolumeClaimTemplate:
    storageClassName: ibmc-vpc-block-10iops-tier
  microServiceSecurity: certManager
  #platformEndpointCASecret:
  #  secretName:
  #consumerEndpointCASecret:
  #  secretName:
  certManagerIssuer:
    name: selfsigning-issuer
    kind: Issuer
  license:
    accept: true
    use: nonproduction
    #license: 'L-AMGN-4YQ9TJ'
    license: L-CXFF-XRSP3J
