apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apic-operators
spec:
  generators:
  - list:
      elements:
        - name: apiconnect
          namespace: apic
        - name: datapower
          namespace: apic
        - name: nanogw
          namespace: datapower-nano-system
        - name: ibm-common-services
          namespace: apic
        - name: openshift-cert-manager
          namespace: cert-manager-operator
        - name: cert-utils
          namespace: cert-utils-operator
  template:
    metadata:
      name: '{{name}}-operator'
      labels:
        group: applications
      annotations:
        argocd.argoproj.io/sync-wave: "100"
    spec:
      project: default
      source:
        path: 'components/{{name}}/operator'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          selfHeal: true
