apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apic-operator
  namespace: argocd
  labels:
    group: applications
  annotations:
    argocd.argoproj.io/sync-wave: "100"
spec:
  destination:
    namespace: nanogw
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./components/apic/operator
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
    automated:
      prune: false
      selfHeal: true