apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-gateway-config
  namespace: argocd
spec:
  project: default
  source:
    path: components/envoy/config
  destination:
    namespace: envoy-gateway-system
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
    automated:
      selfHeal: true
