apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-gateway
  namespace: argocd
spec:
  project: default
  source:
    chart: gateway-helm
    repoURL: docker.io/envoyproxy
    targetRevision: v1.7.0
  destination:
    namespace: envoy-gateway-system
    server: https://kubernetes.default.svc
  ignoreDifferences:
  - kind: ConfigMap
    name: envoy-gateway-config
    namespace: envoy-gateway-system
    jsonPointers:
    - /data
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    - RespectIgnoreDifferences=true
    automated:
      prune: true
      selfHeal: true