apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  hosts.override: |
    hosts {
        20.54.238.192 ai.envoy.eu-de.containers.appdomain.cloud
        20.54.238.192 idig.envoy.eu-de.containers.appdomain.cloud
        fallthrough
    }
