apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apic-operands
spec:
  generators:
  - list:
      elements:
        - name: valkey
          namespace: nanogw
          sync-wave: "300"
        - name: nanogw
          namespace: nanogw
          sync-wave: "300"
        # - name: apic
        #   namespace: nanogw
        #   sync-wave: "300"
  template:
    metadata:
      name: '{{name}}'
      labels:
        group: applications
      annotations:
        argocd.argoproj.io/sync-wave: '{{sync-wave}}'
    spec:
      project: default
      source:
        path: 'envs/iks/nonprod/{{name}}/'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          selfHeal: true
