apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apic-operands
spec:
  generators:
  - list:
      elements:
        - name: envoy
          namespace: envoy-gateway-system
          sync-wave: "300"
        - name: valkey
          namespace: idig
          sync-wave: "300"
        #- name: idig
        #  namespace: idig
        #  sync-wave: "300"
  template:
    metadata:
      name: '{{name}}'
      labels:
        group: applications
      annotations:
        argocd.argoproj.io/sync-wave: '{{sync-wave}}'
    spec:
      project: default
      source:
        path: 'envs/aks/nonprod/{{name}}/'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      ignoreDifferences:
      - group: analytics.apiconnect.ibm.com
        kind: AnalyticsCluster
        managedFieldsManagers:
        - manager
        jqPathExpressions:
        - .metadata.annotations["com.ibm.apiconnect/analytics-upgraded-version"]
        - .metadata.annotations["argocd.argoproj.io/sync-options"]
        - .metadata.annotations["argocd.argoproj.io/tracking-id"]
      - group: devportal.apiconnect.ibm.com
        kind: DevPortalCluster
        managedFieldsManagers:
        - manager
        jqPathExpressions:
        - .metadata.annotations["argocd.argoproj.io/sync-options"]
        - .metadata.annotations["argocd.argoproj.io/tracking-id"]
      - group: nanogateway.apiconnect.ibm.com
        kind: NanoGatewayCluster
        managedFieldsManagers:
        - manager
      syncPolicy:
        automated:
          selfHeal: true
