apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apic-operands
spec:
  generators:
  - list:
      elements:
        - name: envoy
          namespace: envoy-gateway-system
          sync-wave: "300"
        - name: valkey
          namespace: idig
          sync-wave: "300"
        #- name: idig
        #  namespace: idig
        #  sync-wave: "300"
  template:
    metadata:
      name: '{{name}}'
      labels:
        group: applications
      annotations:
        argocd.argoproj.io/sync-wave: '{{sync-wave}}'
    spec:
      project: default
      source:
        path: 'envs/aks/nonprod/{{name}}/'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          selfHeal: true
