kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: apic-argo-role
rules:
  - verbs:
      - '*'
    apiGroups:
      - autoscaling
      - apps
      - batch
      - cert-manager.io
      - tekton.dev
      - logging.openshift.io
      - operator.autoscaling.openshift.io
      - networking.k8s.io
      - monitoring.coreos.com
      - operator.ibm.com
      - apiconnect.ibm.com
      - datapower.ibm.com
      - management.apiconnect.ibm.com
      - nanogateway.apiconnect.ibm.com
      - nano.datapower.ibm.com
      - gateway.apiconnect.ibm.com
      - valkey.datapower.ibm.com
      - rbac.authorization.k8s.io
      - external-secrets.io
      - generators.external-secrets.io
      - operator.external-secrets.io
    resources:
      - '*'