kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: idig-argo-role
rules:
  # Cert-manager
  - verbs: ['*']
    apiGroups: [cert-manager.io]
    resources: ['*']

  # External Secrets
  - verbs: ['*']
    apiGroups: [external-secrets.io]
    resources: ['*']

  - verbs: ['*']
    apiGroups: [generators.external-secrets.io]
    resources: ['*']

  - verbs: ['*']
    apiGroups: [operator.external-secrets.io]
    resources: ['*']

  # Gateway API
  - verbs: ['*']
    apiGroups: [gateway.networking.k8s.io]
    resources: ['*']

  # Envoy Gateway
  - verbs: ['*']
    apiGroups: [gateway.envoyproxy.io]
    resources: ['*']

  # IBM / APIC operands
  - verbs: ['*']
    apiGroups:
      - operator.ibm.com
      - apiconnect.ibm.com
      - datapower.ibm.com
      - management.apiconnect.ibm.com
      - nanogateway.apiconnect.ibm.com
      - nano.datapower.ibm.com
      - gateway.apiconnect.ibm.com
      - valkey.datapower.ibm.com
    resources: ['*']

  # Monitoring
  - verbs: ['*']
    apiGroups: [monitoring.coreos.com]
    resources: ['*']
