apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:

  - apic-argo-role.yaml
  - apic-argo-rb.yaml

  - operators/cert-manager-operator.yaml
  - operators/external-secrets-operator.yaml

  - operators/nanogw-operator.yaml
  - operators/apic-operator.yaml
  - operators/valkey-operator.yaml

  - operands/all-operands.yaml
 

patches:
- target:
    group: argoproj.io
    kind: Application
    labelSelector: group=applications
  patch: |-
    - op: add
      path: /spec/source/repoURL
      value: https://github.com/louhaz/nano-gateway.git
    - op: add
      path: /spec/source/targetRevision
- target:
    group: argoproj.io
    kind: ApplicationSet
  patch: |-
    - op: add
      path: /spec/template/spec/source/repoURL
      value: https://github.com/louhaz/nano-gateway.git
    - op: add
      path: /spec/template/spec/source/targetRevision
