apiVersion: devportal.apiconnect.ibm.com/v1beta1
kind: DevPortalCluster
metadata:
  name: idig-devportal
  namespace: idig
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
spec:
  devportalAdminEndpoint:
    gatewayClassName: envoy
  devportalUIEndpoint:
    gatewayClassName: envoy
