apiVersion: datapowerinteractgateway.ibm.com/v1beta1
kind: DatapowerInteractGatewayCluster
metadata:
  name: idig
  namespace: idig
spec:
  nanoGateway:
    mgmtEndpoint:
      gatewayClassName: envoy
