apiVersion: valkey.datapower.ibm.com/v1beta2
kind: Valkey
metadata:
  name:  valkey
  labels:
    app.kubernetes.io/name: valkey
    helm.sh/chart: valkey-1.0.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: valkey
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/component: middleware
  annotations:    
spec:
  kubernetesConfig:
    podSecurityContext:
      fsGroup: 1000
    image: "cp.icr.io/cp/datapower/valkey:8.1.4@sha256:228954da8acaa22736279c477c4e5780284e306431eb2bf7bbb61710cfc5ec47"
    imagePullPolicy: "Always"
    imagePullSecrets: 
    - name: ibm-entitlement-key
    resources: 
      requests: 
        cpu: "100m"
    valkeySecret:
      name: "valkey-secret"
      key: "password"
    persistentVolumeClaimRetentionPolicy: 
      whenDeleted: Delete
      whenScaled: Retain
  TLS:
    ca: "ca.crt"
    cert: "tls.crt"
    key: "tls.key"
    secret:
      secretName: "valkey-tls-secret"
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: ibmc-vpc-block-10iops-tier
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
